service: params

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

functions:
  one:
    handler: handler.one
    parameters:
      ENV_VAR_ONE: ParamValue
    events:
      - http:
          path: one
          method: get
  two:
    handler: handler.two
    parameters:
      ENV_VAR_TWO: ParamValue
    events:
      - http:
          path: two
          method: get

resources:
  Resources:
    ParamValue:
      Type: AWS::SSM::Parameter
      Properties:
        Description: Dynamic parameter
        Name: ParamValue
        Type: String
        Value: hello, dave

plugins:
  - '@agiledigital/serverless-param-subscriber'
